export const WALLET_FLOW_NAME = "WALLET_FLOW_NAME"
export const WALLET_QUEUE_NAME = "WALLET_QUEUE_NAME"
export const WALLET_TASK_QUEUE_NAME = "WALLET_TASK_QUEUE_NAME"

export const WALLET_BALANCE_BITCOIN_NAME = "WALLET_BALANCE_BITCOIN_NAME"
export const WALLET_BALANCE_EVM_NAME = "WALLET_BALANCE_EVM_NAME"
export const WALLET_BALANCE_BITCOIN_CASH_NAME = "WALLET_BALANCE_BITCOIN_CASH_NAME"
export const WALLET_BALANCE_LITECOIN_NAME = "WALLET_BALANCE_LITECOIN_NAME"
export const WALLET_BALANCE_SOLANA_NAME = "WALLET_BALANCE_SOLANA_NAME"
export const WALLET_BALANCE_TRON_NAME = "WALLET_BALANCE_TRON_NAME"

export const WALLET_CHILDREN_QUEUES = [
  WALLET_BALANCE_BITCOIN_NAME,
  WALLET_BALANCE_EVM_NAME,
  WALLET_BALANCE_BITCOIN_CASH_NAME,
  WALLET_BALANCE_LITECOIN_NAME,
  WALLET_BALANCE_SOLANA_NAME,
  WALLET_BALANCE_TRON_NAME
]